### PR TITLE
Some improvements

### LINKED ISSUE #46: Could not compile scoped-tls on nighly
Hello, this project seems really promising! But I'm having trouble installing the tool. Please let me know if I'm doing something wrong. Here is my error message:

```
olega@DESKTOP-B47K2S5 MINGW64 ~/Documents/Rust/udemy (master)
$ rustup default nightly
info: using existing install for 'nightly-x86_64-pc-windows-msvc'
info: default toolchain set to 'nightly-x86_64-pc-windows-msvc'

  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.40.0-nightly (518deda77 2019-10-18)


olega@DESKTOP-B47K2S5 MINGW64 ~/Documents/Rust/udemy (master)
$ cargo install cargo-modules
    Updating crates.io index
  Installing cargo-modules v0.4.4
   Compiling winapi v0.3.8
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
   Compiling semver-parser v0.7.0
   Compiling arrayvec v0.4.12
   Compiling scopeguard v0.3.3
   Compiling bitflags v1.2.1
   Compiling libc v0.2.65
   Compiling nodrop v0.1.14
   Compiling memoffset v0.2.1
   Compiling rand_core v0.4.2
   Compiling log v0.4.8
   Compiling unicode-width v0.1.6
   Compiling rustc-rayon-core v0.1.2
   Compiling byteorder v1.3.2
   Compiling stable_deref_trait v1.1.1
   Compiling smallvec v0.6.10
   Compiling rustc-rayon v0.1.2
   Compiling autocfg v0.1.6
   Compiling either v1.5.3
   Compiling proc-macro2 v0.4.30
   Compiling rustc-ap-graphviz v373.0.0
   Compiling unicode-xid v0.1.0
   Compiling cgmath v0.16.1
   Compiling syn v0.15.44
   Compiling unicode-segmentation v1.3.0
   Compiling rustc-ap-rustc_target v373.0.0
   Compiling approx v0.1.1
   Compiling scoped-tls v0.1.2
error: allow_internal_unstable expects list of feature names
  --> C:\Users\olega\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-0.1.2\src\lib.rs:71:1
   |
71 | #[allow_internal_unstable]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

   Compiling rgb v0.8.14
error: could not compile `scoped-tls`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-modules v0.4.4`, intermediate artifacts can be found at `C:\Users\olega\AppData\Local\Temp\cargo-installPd81Wa`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by hmvp**
- This should make it compile on a recent nightly again and fix #46 #44 
- Improved some test code
- Improved some 2018 edition use parsing

### CODE REVIEW

**Comment by regexident** [comment]
LGTM. 👍

**Comment by TheButlah** [comment]
Any updates on this? Just tried to install your package but I get the bug in #46, would be awesome to use this project.

**Comment by pksunkara** [comment]
@regexident please merge and release

**Comment by regexident** [comment]
@pksunkara as long as the build fails to build there is no point in merging and releasing, for that  matter, unfortunately.

The `rustc_ap_syntax` crate we are forced to depend on (for getting access to the Rust AST) is unstable and behaves like a moving target, constantly introducing breaking changes.

**Comment by regexident** [comment]
And with that we have another patch release: 0.4.5 🎉

**Pull request merged**
