### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by regexident**
Fixes https://github.com/regexident/cargo-modules/issues/67

### CODE REVIEW

**Comment by regexident** [comment]
Hm, interesting. This is working fine on macOS with 
```terminal
$ rustc --version
rustc 1.50.0-nightly (0f6f2d681 2020-12-06)
```

🤔

**Comment by ArekPiekarz** [comment]
@regexident I found this problem on Manjaro 20.2.

**Comment by regexident** [comment]
@ArekPiekarz could you by chance check out the `fix` branch and check if it compiles for you?
I can't reproduce the errors on my system and they don't really make much sense to me either. 😕

**Comment by ArekPiekarz** [comment]
@regexident I tested the "fix" branch and it fails with a different error:
```
cargo +nightly build --release
(...)
   Compiling rustc-ap-rustc_data_structures v692.0.0
   Compiling rustc-ap-rustc_span v692.0.0
   Compiling rustc-ap-rustc_ast v692.0.0
   Compiling rustc-ap-rustc_target v692.0.0
   Compiling rustc-ap-rustc_feature v692.0.0
   Compiling rustc-ap-rustc_lint_defs v692.0.0
   Compiling rustc-ap-rustc_ast_pretty v692.0.0
   Compiling rustc-ap-rustc_errors v692.0.0
   Compiling rustc-ap-rustc_session v692.0.0
   Compiling rustc-ap-rustc_parse v692.0.0
   Compiling cargo-modules v0.4.10 (/home/user/dev/project/forks/cargo-modules)
error[E0425]: cannot find function `walk_mac_call` in module `visit`
   --> src/builder.rs:164:16
    |
164 |         visit::walk_mac_call(self, mac);
    |                ^^^^^^^^^^^^^ help: a function with a similar name exists: `walk_mac_args`
    | 
   ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_ast-692.0.0/src/visit.rs:897:1
    |
897 | pub fn walk_mac_args<'a, V: Visitor<'a>>(visitor: &mut V, args: &'a MacArgs) {
    | ---------------------------------------------------------------------------- similarly named function `walk_mac_args` defined here

error[E0425]: cannot find function `walk_mac_call` in module `visit`
   --> src/ng/analysis.rs:211:16
    |
211 |         visit::walk_mac_call(self, macro_);
    |                ^^^^^^^^^^^^^ help: a function with a similar name exists: `walk_mac_args`
    | 
   ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_ast-692.0.0/src/visit.rs:897:1
    |
897 | pub fn walk_mac_args<'a, V: Visitor<'a>>(visitor: &mut V, args: &'a MacArgs) {
    | ---------------------------------------------------------------------------- similarly named function `walk_mac_args` defined here

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `cargo-modules`

To learn more, run the command again with --verbose.
```

**Pull request merged**
