### PR TITLE
chore: use the latest `rust-analyzer` related crates, version `0.0.215`.

### PR DESCRIPTION
**Pull request by wangziling**
Use the latest `rust-analyzer` related crates.

The enum `ra_ap_project_model::ProjectWorkspace` had been refactored at the version `v0.0.212` against `v0.0.211`.

v0.0.211: https://docs.rs/ra_ap_project_model/0.0.211/ra_ap_project_model/enum.ProjectWorkspace.html
v0.0.212: https://docs.rs/ra_ap_project_model/0.0.212/ra_ap_project_model/struct.ProjectWorkspace.html

### CODE REVIEW

**Comment by wangziling** [comment]
Seems here exists some clippy errors 😮.

**Comment by regexident** [comment]
Would you mind rebasing this onto `main` with linear history?

**Comment by wangziling** [comment]
🙃 let me create a new branch and new PR...

I don't know why it cannot process on `rebase` operation...

**Comment by wangziling** [comment]
> Would you mind rebasing this onto `main` with linear history?

let me create a new branch and new PR...

I don't know why it cannot process on rebase operation...

'Cause nearly I havn't used the rebase operation in the working life, I only used the merge operation('Cause we need to record the meaningful branch name with jira-or-something on the commit message).

So I'm afaid to forcibly do something with currently-unfamiliar rebase operation and let your main branch graph or history be chaos, so I decide to create a new branch which is checked out from the upstream/main and rise up a new PR.

I will deep dive into learning the `rebase` operation latter.

**Pull request closed without merging**
