### PR TITLE
REWRITE ALL THE THINGS

### PR DESCRIPTION
**Pull request by regexident**
I started refactoring the project, moving things from depending on 'rustc_…' (**rustc** internals) to 'ra_ap_…' (**rust-analyzer** internals)

Progress:

- [x] `$ cargo modules tree` (now called `$ cargo modules generate tree`)
- [x] `$ cargo modules graph` (now called `$ cargo modules generate graph`)

Since we're moving from performing analysis on a project's AST to analysis on its HIR we should be able to fix a bunch more issues in the long term, which right now see kind of hard if not impossible to fix:

- [x] [Edition 2018 Support](#34)
- [x] [Doesn't understand the `crate` keyword](#29)
- [ ] [Doesn't understand cfg-if](#41)
- [x] [Differentiate between modules with the same name](#28)
- [x] [Support for cargo workspaces](#8)

It should also make these features feasible:

- [x] [Feature request: Option to list all public types](#48)
- [ ] [Identify cycles between imports](#18)
- [x] [Analyze crates in non-test mode](#20)

---

(Once finished this will fix https://github.com/regexident/cargo-modules/issues/63.)

### CODE REVIEW

**Comment by regexident** [comment]
Orphans working again in `cargo modules tree`

**Comment by kvark** [comment]
Please let me know when it would make sense to start testing it! Super excited to get that ball rolling on [WR](https://github.com/servo/webrender), once available.
Today, running the `tree` command isn't producing anything for me, just:
> compositor_windows: pub

**Comment by regexident** [comment]
@kvark: right now the target selection does a very, very hack-ish "select first library found", iirc.

As such it could be possible that the logic somehow picked the [compositor-windows](https://github.com/servo/webrender/tree/d5d96e316421ee87faf2aebfa1ab8f003448fdb0/example-compositor/compositor-windows) package as target. The `compositor-windows` crate contains just a single modules, which matches your terminal output.

I still need to add a proper CLI target selection feature, as well as add proper support for workspace handling.

Target selection is the next thing I'll be working on, as for the `cargo modules graph` logic I'll need to do some more reading up on how rust-analyzer handles imports (I also think the graph should not be restricted to explicit imports, but any used paths per module).

**Comment by kvark** [comment]
Ok, I see. Thank you for the info! Graph is the stuff I need, and I'm waiting eagerly for it to be available :)

**Comment by regexident** [comment]
@kvark These latest commits add support for graph generation (as well as graph shrinking for large projects) and workspaces.

After the rewrite cargo-modules will have two new root-level commands:

## `cargo modules generate …`

The existing `cargo modules tree` and `cargo modules graph` have been moved into `cargo modules generate …`, resulting in:

### `cargo modules generate tree`

Changes:

- support for all new `pub(…)` types.
- support for printing types (fixing #48).
- a visual face-lift bringing us nicer colors:
  - **visibility** is indicated by `red` (least visible) to `green` (most visible).
  - **orphans** (`--with-orphans`) are purple.
  - **types** (`--with-types`) are dimmed.

### `cargo modules generate graph`

Changes:

- support for all new `pub(…)` types.
- support for printing types (fixing #48).
- a visual face-lift bringing us nicer colors:
  - **visibility** is indicated by `red` (least visible) to `green` (most visible).
  - **orphans** (`--with-orphans`) are purple.
  - **types** (`--with-types`) are dimmed.
  - **focused** nodes are cyan.
- support for focusing on a specific node (i.e. graph shrinking):
  - `--focus-on <RUST-PATH>`
  - `--max-depth <INT>`

## `cargo modules check …`

The plan for `cargo modules check …` is to provide linting capabilities (for use in CI).

As such #18 might be made available as `cargo modules check --no-cycles`.

If you want to try the out today then make sure to run with `--release`, e.g.:

```terminal
cargo run --release -- generate tree --with-types --with-orphans --lib
```

And check `--help` for the individual commands for all the options they support respectively.

**Comment by kvark** [comment]
I'm able to get some useful output of this on WebRender! Looking very promising ❤️ 
The difference between "debug" performance and release is staggering!

One thing I noticed so far is the weird "blue" boxes. The appear to have sub-modules of external crates, like "pub mod core::hash" or "pub(crate) mod euclid::rect" (while I'm targeting the "webrender" lib only). I don't care *which* submodules of externnal crates are used, a single "core" block is all I need to see that dependency. Having multiple different blocks here is cluttering the view. Is there an option I missed on how to control this?

Another note, a more general one, is about additional logic that you are considering on top of generating the dependency graph. For example, you are working on the cycle detection for linting. This is great! What we have is: we *know* they are cycles, and we want to refactor them, but how do we know where to start? I.e. it would be great if the tool was able to point out to the *worst* modules or their connections. Not sure what part of the graph theory that would be, some measure of connectivity/loop-ness?

**Comment by regexident** [comment]
> I'm able to get some useful output of this on WebRender! Looking very promising ❤️

Awesome, that's a good start! So the workspace support seems to be working for you then.

> The difference between "debug" performance and release is staggering!

It is indeed! 😄

> One thing I noticed so far is the weird "blue" boxes. They appear to have sub-modules of external crates, like "pub mod core::hash" or "pub(crate) mod euclid::rect" (while I'm targeting the "webrender" lib only). I don't care which submodules of externnal crates are used, a single "core" block is all I need to see that dependency. Having multiple different blocks here is cluttering the view. Is there an option I missed on how to control this?

I wasn't sure if the full path would be useful for people. But I have to agree that in almost all scenarios having a node for the extern crate alone would be desirable.

I've pushed some commits that cause uses of items from extern crate to get collapsed into their extern crates. If people end wanting the old behavior, too, then I'll just add a flag for it.

I've also made node names in `generate graph` always be full paths.

> Another note, a more general one, is about additional logic that you are considering on top of generating the dependency graph. For example, you are working on the cycle detection for linting. This is great! What we have is: we know they are cycles, and we want to refactor them, but how do we know where to start? I.e. it would be great if the tool was able to point out to the worst modules or their connections. Not sure what part of the graph theory that would be, some measure of connectivity/loop-ness?

I think one of the parts of graph theory that might end up being useful for us here is the concept of a [feedback arc set](https://en.wikipedia.org/wiki/Feedback_arc_set), specifically the [minimum feedback arc set](https://en.wikipedia.org/wiki/Feedback_arc_set#Minimum_feedback_arc_set):

> [Wikipedia](https://en.wikipedia.org/wiki/Feedback_arc_set): "A **feedback arc set** (FAS) or feedback edge set is a **set of edges which, when removed from the graph, leaves an acyclic graph**. Put another way, it is a set containing at least one edge of every cycle in the graph. In graph theory, a directed graph may contain directed cycles, a closed one-way path of edges. […] Sometimes it is desirable to **drop as few edges as possible**, obtaining a **minimum feedback arc set** (MFAS), or dually a maximum acyclic subgraph. **This is a hard computational problem, for which several approximate solutions have been devised.**"

However I believe that a heuristics-based cycle-detector might already bring us a long way.

**Comment by regexident** [comment]
> So looks like we are missing a bunch of links in the graph?

That's certainly possible.

I'm using [`ra_ap_hir::Module::scope`](https://docs.rs/ra_ap_hir/0.0.34/ra_ap_hir/struct.Module.html#method.scope) to obtain a set of all the item visible in the given module as it seems to be the easiest way to extract a `use`-graph.

But I'm currently only matching against the `ScopeDef::ModuleDef` variant, which might be insufficient.

Also it only provides a module-level granularity. We might want to go down to the type-level though. I just haven't yet figured out how `ra_ap_hir` would allow me to access that kind of information.

**Comment by kvark** [comment]
Thank you for the update! Here is some more feedback.

1) the external dependencies are now merged, but they still occupy a whole lot of space. Would it be possible to have a command line option to omit those nodes completely? I.e. if I'm interested in reducing the module graph complexity, I don't care much about the external links, I'm mostly concerned about the loops within the root crate only.

1a) if there are no external crates, can we omit the `<crate_name>::` prefix from all nodes? That would make them shorter and easier to read.

2) the issue about missing links is still there. [Here](https://github.com/servo/webrender/blob/daff837bfdb442ad18b6929ac9a52af5e4c332a9/webrender/src/prim_store/text_run.rs#L21) is an example of a link that doesn't register (from `crate::prim_store::text_run` to `crate::space`).

3) I wonder if there are any external tools (a web page?) that would render a given Dot file and allow to focus on different nodes. That would be much more convenient than re-running the `cargo-modules` and re-generating the graph each time with a new focus.

**Comment by regexident** [comment]
1) Done. I already had worked on this in my local checkout. 😄

2) This should also be fixed now. I was dropping "use" edges to types if `--with-types` was absent, instead of redirecting them to their modules. 😇

3) That's something I've thought about, too. 👍🏻 I'm not a web-dev though (neither back, not front-end), so I've been focusing —for now— on getting the core functionality working. A browser-based UI would also be rather useful for visualizing dependency cycles and providing cycle-breaking suggestions with instant visual previews, I think.

**Comment by regexident** [comment]
We now have support for filtering conditionally excluding/including tests via `--with-tests`, which are excluded by default.

**Comment by kvark** [comment]
Awesome, I see way more links now! Gotta figure out how to work with this. The `dot` generated picture looks pretty dense:
wr-dependencies-fragment

**Comment by kvark** [comment]
I'm having limited success with visualizing things (currently toying with Gephi), but most of all I'm surprised how difficult it is to visualize the dependency cycles... given that Dot is a standard format, and cycle detection is a textbook problem that's long solved. It's amazing how poor those tools are, at least in open-source space.

Also found something similar to cargo-modules but for Dart, where we could borrow some ideas - https://github.com/OlegAlexander/lakos

**Comment by regexident** [comment]
> I wonder if there are any external tools (a web page?) that would render a given Dot file and allow to focus on different nodes. That would be much more convenient than re-running the cargo-modules and re-generating the graph each time with a new focus.

Most if not all commands of cargo-modules will be processing a single generated petgraph as a single source of truth. So I'm thinking about adding a `--cache FILE` option for caching the extracted graph, along with a `--clean` option for deleting/regenerating it from source.

> Awesome, I see way more links now! Gotta figure out how to work with this. The dot generated picture looks pretty dense:
> wr-dependencies-fragment

Well, you better start chopping away a bunch of code. 😄
Joking aside, the fact that every edge has a label makes it even worse. But without them one would need some kind of legend. And changing the layout algorithm tends to break that kind of stuff. So kept them in for now. Add an `--without-edge-labels` option, maybe?

> I'm having limited success with visualizing things (currently toying with Gephi), but most of all I'm surprised how difficult it is to visualize the dependency cycles... given that Dot is a standard format, and cycle detection is a textbook problem that's long solved. It's amazing how poor those tools are, at least in open-source space.

My plan is to perform cycle detection on the petgraph via [`fn kosaraju_scc(…)`](https://docs.rs/petgraph/0.5.1/petgraph/algo/fn.kosaraju_scc.html) or  [`fn tarjan_scc(…)`](https://docs.rs/petgraph/0.5.1/petgraph/algo/fn.tarjan_scc.html) and then make the cycle's edges red or something.

Also currently the nodes are colored by their visibility (with a gradient from red=least visible to green=most visible). I'd like to have an option like `--node-color [none | visibility | instability | coupling | nccd | sloc]`, since visibility certainly isn't the only interesting metric to visualize.

> Also found something similar to cargo-modules but for Dart, where we could borrow some ideas - https://github.com/OlegAlexander/lakos

A `cargo modules generate metrics` command certainly is something I wanted to add at some point, too. As well as a corresponding `cargo modules check metrics` with `--max-nccd 1.5`, `--no-cycles` and the like for use in CI.

I've also looked into visualizing each module (and its children) as dot subgraphs, with a label and border. It's on my to-do list.

---

For now I think I'll put a feature freeze on this PR to get it merged asap. I'll then create appropriate issues/milestones to track the outstanding issues and missing features.

**Comment by kvark** [comment]
That's very informative, thank you! And I fully agree that this needs to be landed, it's great, and it's already helpful ❤️

**Comment by regexident** [comment]
@kvark Commit https://github.com/regexident/cargo-modules/pull/66/commits/f7d226f45949f54b13a8c6bf7a6c08e09db6001d removed any remaining [`ra_ap_hir`](https://docs.rs/ra_ap_hir/0.0.35/ra_ap_hir/) values from the graph's nodes, which were preventing persisting the graph to disk.

As such adding a `--cache <FILE>` (and a complementary `--ignore-cache`, I suppose) should now just be a matter of some minor elbow grease.

The idea would be to have cargo-modules skip the `src -> AST -> HIR -> graph` steps and jump straight to the graph, loading it from disk if a previously persisted graph is found at `<FILE>`. The persisted graph would be tagged with cargo-module's current version and outdated caches ignored.

**Comment by kvark** [comment]
So that would allow me to re-launch it with different focus points quickly? Or is it something else?

**Comment by regexident** [comment]
Once implemented, yes. That's the idea at least.

But first I want to update the readme to reflect the changes, maybe add a CHANGES file, merge this PR and publish a `v0.5`.

Just wanted to update you on the progress.

**Review by pksunkara — COMMENTED** [review]
It looks like you implemented the hir visitor, but I have been trying to find that in this code (so that I can extract it as we talked about) and gave up lol.

**Comment by regexident** [comment]
@pksunkara I did, but it ended up being cleaner for my use-case to just explicitly drive the module walking via recursion, so I removed the visitor  in https://github.com/regexident/cargo-modules/pull/66/commits/d9ed9aee930c780ff8e61343e73ee31df16b41ba. 😄

I do still plan however to create a PR with it for [cargo-up](https://github.com/pksunkara/cargo-up), as it should be quite useful for others. I just haven't gotten to it yet. 😇

**Comment by pksunkara** [comment]
🙏 

I am just happy that someone else is finally using the `ra_ap_*` crates. I put quite a bit of work into getting that release process done.

**Pull request merged**
